services:
  jenkins:
    container_name: jenkins
    image: mlucken/jenkins-arm:latest
    ports:
      - 80:8080
    volumes:
      - jenkinsvol:/var/jenkins_home
    restart: always
volumes:
  jenkinsvol:
